name: hsinstall
version: '2.1'
synopsis: Install Haskell software
description: This is a tool for deploying software projects into directory structures suitable for installation on a system. It builds upon the `stack install` command and adds more features. It's also a tool for easier AppImage creation.
license: ISC
author: Dino Morelli
maintainer: Dino Morelli <dino@ui3.info>
copyright: 2016-2018 Dino Morelli
category: Utility
extra-source-files:
- changelog.md
- doc/hcar/hsinstall.tex
- .gitignore
- package.yaml
- README.md
- resources/unix-terminal.svg
- stack.yaml
- util/resources/appimage/hsinstall.desktop
- util/resources/appimage/hsinstall.svg

github: dino-/hsinstall

ghc-options:
- -fwarn-tabs
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
- base >= 4.8 && < 5.0

library:
  source-dirs: src/lib
  dependencies:
  - directory
  - filepath

executables:
  hsinstall:
    source-dirs: src/app
    main: hsinstall.hs
    dependencies:
    - Cabal
    - directory
    - filepath
    - here
    - hsinstall
    - process
