name: hsinstall
version: '2.5'
synopsis: Install Haskell software
description: This is a tool for deploying software projects into directory structures suitable for installation on a system. It builds upon the `stack install` command and adds more features. It's also a tool for easier AppImage creation.
license: ISC
author: Dino Morelli
maintainer: Dino Morelli <dino@ui3.info>
copyright: 2016-2019 Dino Morelli
category: Utility
extra-source-files:
- changelog.md
- doc/hcar/hsinstall.tex
- .gitignore
- pack/share/applications/hsinstall.desktop
- pack/share/hsinstall/resources/unix-terminal.svg
- pack/share/icons/hicolor/scalable/apps/hsinstall.svg
- package.yaml
- README.md
- stack.yaml

github: dino-/hsinstall

ghc-options:
- -fwarn-tabs
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
- base >= 4.8 && < 5.0
- directory
- filepath

library:
  source-dirs: src/lib

executables:
  hsinstall:
    source-dirs: src/app
    main: hsinstall.hs
    dependencies:
    - ansi-wl-pprint
    - Cabal
    - fmt
    - heredoc
    - hsinstall
    - optparse-applicative
    - process
    - safe-exceptions
