name: hsinstall
version: '2.0'
synopsis: Install Haskell software
description: This is a utility to install Haskell programs on a system using stack. Even though stack has an `install` command, I found it to be not enough for my needs. This software tries to install the binaries, the LICENSE file and also the resources directory if it finds one. There is also an optional library component to assist with locating installed data files at runtime.
license: ISC
author: Dino Morelli
maintainer: Dino Morelli <dino@ui3.info>
copyright: 2016-2017 Dino Morelli
category: Utility
# data-files: resources/foo
extra-source-files:
- changelog.md
- doc/hcar/hsinstall.tex
- README.md
# - resources/foo
- stack.yaml

github: dino-/hsinstall

ghc-options:
- -fwarn-tabs
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

# default-extensions:
# - OverloadedStrings

dependencies:
- base >= 4.8 && < 5.0

library:
  source-dirs: src/lib
  dependencies:
  - directory
  - filepath

executables:
  hsinstall:
    source-dirs: src/hsinstall
    main: Main.hs
    dependencies:
    - Cabal
    - directory
    - filepath
    - hsinstall
    - process
